services:
  - type: web
    name: future-dream-demo
    env: service
    plan: free
    repo: https://github.com/gguatit/Future_Dream_Demo
    branch: main
    buildCommand: cd demo && mvn -DskipTests package
    startCommand: java -Dserver.port=$PORT -jar demo/target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: "-Xms128m -Xmx512m"
